spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems_user?allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: admin

  jwt:
    private.key: classpath:app.key
    public.key: classpath:app.pub