spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems_user
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  jwt:
    private.key: classpath:app.key
    public.key: classpath:app.pub