database:
  ip: ${DB_IP:localhost}
  port: ${DB_PORT:3306}
  user: ${DB_USER:root}
  password: ${DB_PASSWORD:admin}
  name: ${DB_DBNAME:ems_user}

device:
  container:
    name: ${DEVICE_CONTAINER_NAME:ems-device-container}

spring:
  datasource:
    url: jdbc:mysql://${database.ip}:${database.port}/${database.name}
    username: ${database.user}
    password: ${database.password}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  jwt:
    private.key: classpath:app.key
    public.key: classpath:app.pub

server:
  port: 8080