version: '3'
services:
  emsdevice:
    image: ems-simulator-image
    container_name: ems-simulator-container
    ports:
      - "8083:8083"
    networks:
      - mynetwork

networks:
  mynetwork:
    name: "mynetwork"
    external: true  # So that Docker accepts the fact that the network was not created by docker compose, but was created previously