version: '3'
services:
  emsdevice:
    image: ems-chat-image
    container_name: ems-chat-container
    ports:
      - "8084:8084"
    networks:
      - mynetwork

networks:
  mynetwork:
    name: "mynetwork"
    external: true  # So that Docker accepts the fact that the network was not created by docker compose, but was created previously