version: '3'
services:
  emsdevice:
    image: ems-device-image
    container_name: ems-device-container
    ports:
      - "8081:8081"
    networks:
      - mynetwork

networks:
  mynetwork:
    name: "mynetwork"
    external: true  # So that Docker accepts the fact that the network was not created by docker compose, but was created previously